sudo: required
language: go

branches:
  only:
    - master
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip

env:
  global:
    - GOARCH=amd64
    - BLAS_LIB=OpenBLAS
    - TRAVISTEST=true
    - CUDA=8.0.61-1

# Cache used to persist the compiled BLAS library between CI calls.
cache:
  directories:
  - .travis/OpenBLAS.cache

before_install:
  - go get github.com/mattn/goveralls

go_import_path: gorgonia.org/gorgonia

# Install the appropriate blas library (if any) and associated gonum software.
install:
- travis_wait source ${TRAVIS_BUILD_DIR}/.travis/$TRAVIS_OS_NAME/install.sh

script: 
- source ${TRAVIS_BUILD_DIR}/.travis/$TRAVIS_OS_NAME/$BLAS_LIB/test.sh

matrix:
  allow_failures:
    - go: tip
