
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/awalterschulze/gographviz"
  version = "~2.0.0"

[[constraint]]
  version = "~0.8.0"
  name = "gorgonia.org/cu"

[[constraint]]
  name = "github.com/chewxy/hm"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/chewxy/math32"
  version = "~1.0.0"

[[constraint]]
  branch = "master"
  name = "gorgonia.org/vecf32"

[[constraint]]
  branch = "master"
  name = "github.com/chewxy/vecf64"

[[constraint]]
  branch = "master"
  name = "github.com/leesper/go_rng"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "~0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/xtgo/set"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[[constraint]]
  branch = "master"
  name = "gonum.org/v1/gonum"

[[constraint]]
  branch = "master"
  name = "gonum.org/v1/netlib"

[[constraint]]
  version = "~v0.8.0"
  name = "gorgonia.org/tensor"
